In [1]:
import pandas as pd

In [3]:
import numpy as np

In [23]:
df_train = pd.read_csv('train.csv')

In [25]:
df_train = df_train[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [27]:
df_train

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [35]:
df_train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [29]:
df_train['Sex_int'] = df_train['Sex'].replace({'male':1,'female':0})

C:\Users\ramac\AppData\Local\Temp\ipykernel_13940\4164722013.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['Sex_int'] = df_train['Sex'].replace({'male':1,'female':0})

In [39]:
df_train['Embarked_int'] = df_train['Embarked'].replace({'S':1,'C':2,'Q':3})

C:\Users\ramac\AppData\Local\Temp\ipykernel_13940\3762101794.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['Embarked_int'] = df_train['Embarked'].replace({'S':1,'C':2,'Q':3})

In [41]:
df_train

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex_int,Embarked_int
0,0,3,male,22.0,1,0,7.2500,S,1,1.0
1,1,1,female,38.0,1,0,71.2833,C,0,2.0
2,1,3,female,26.0,0,0,7.9250,S,0,1.0
3,1,1,female,35.0,1,0,53.1000,S,0,1.0
4,0,3,male,35.0,0,0,8.0500,S,1,1.0
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,1,1.0
887,1,1,female,19.0,0,0,30.0000,S,0,1.0
888,0,3,female,NaN,1,2,23.4500,S,0,1.0
889,1,1,male,26.0,0,0,30.0000,C,1,2.0
890,0,3,male,32.0,0,0,7.7500,Q,1,3.0

In [59]:
df_train = df_train.fillna(0)

In [61]:
df_train_features = df_train[['Pclass','Age','SibSp','Parch','Fare','Sex_int','Embarked_int']]

In [63]:
df_train_target = df_train['Survived']

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [72]:
clf = RandomForestClassifier(n_estimators = 200, random_state = 42)

In [76]:
clf.fit(df_train_features,df_train_target)

RandomForestClassifier(n_estimators=200, random_state=42)

## Testing Performance

In [120]:
df_test = pd.read_csv('test.csv')

In [122]:
df_test = df_test[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [124]:
df_test

     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0            892       3    male  34.5      0      0    7.8292        Q
1            893       3  female  47.0      1      0    7.0000        S
2            894       2    male  62.0      0      0    9.6875        Q
3            895       3    male  27.0      0      0    8.6625        S
4            896       3  female  22.0      1      1   12.2875        S
..           ...     ...     ...   ...    ...    ...       ...      ...
413         1305       3    male   NaN      0      0    8.0500        S
414         1306       1  female  39.0      0      0  108.9000        C
415         1307       3    male  38.5      0      0    7.2500        S
416         1308       3    male   NaN      0      0    8.0500        S
417         1309       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]

In [126]:
df_test['Sex_int'] = df_test['Sex'].replace({'male':1,'female':0})

C:\Users\ramac\AppData\Local\Temp\ipykernel_13940\3228916345.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test['Sex_int'] = df_test['Sex'].replace({'male':1,'female':0})

In [128]:
df_test['Embarked_int'] = df_test['Embarked'].replace({'S':1,'C':2,'Q':3})

C:\Users\ramac\AppData\Local\Temp\ipykernel_13940\3703366418.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test['Embarked_int'] = df_test['Embarked'].replace({'S':1,'C':2,'Q':3})

In [130]:
df_test

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex_int,Embarked_int
0,892,3,male,34.5,0,0,7.8292,Q,1,3
1,893,3,female,47.0,1,0,7.0000,S,0,1
2,894,2,male,62.0,0,0,9.6875,Q,1,3
3,895,3,male,27.0,0,0,8.6625,S,1,1
4,896,3,female,22.0,1,1,12.2875,S,0,1
...,...,...,...,...,...,...,...,...,...,...
413,1305,3,male,NaN,0,0,8.0500,S,1,1
414,1306,1,female,39.0,0,0,108.9000,C,0,2
415,1307,3,male,38.5,0,0,7.2500,S,1,1
416,1308,3,male,NaN,0,0,8.0500,S,1,1
417,1309,3,male,NaN,1,1,22.3583,C,1,2

In [132]:
df_test = df_test[['PassengerId','Pclass','Sex_int','Age','SibSp','Parch','Fare','Embarked_int']]

In [134]:
df_test

     PassengerId  Pclass  Sex_int   Age  SibSp  Parch      Fare  Embarked_int
0            892       3        1  34.5      0      0    7.8292             3
1            893       3        0  47.0      1      0    7.0000             1
2            894       2        1  62.0      0      0    9.6875             3
3            895       3        1  27.0      0      0    8.6625             1
4            896       3        0  22.0      1      1   12.2875             1
..           ...     ...      ...   ...    ...    ...       ...           ...
413         1305       3        1   NaN      0      0    8.0500             1
414         1306       1        0  39.0      0      0  108.9000             2
415         1307       3        1  38.5      0      0    7.2500             1
416         1308       3        1   NaN      0      0    8.0500             1
417         1309       3        1   NaN      1      1   22.3583             2

[418 rows x 8 columns]

In [137]:
gender_submission = pd.read_csv('gender_submission.csv')

In [141]:
clf.predict(df_test[['Pclass','Sex_int','Age','SibSp','Parch','Fare','Embarked_int']])

ValueError: The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.