### EDA

In [30]:
import pandas as pd

In [31]:
df_100k = pd.read_csv('apartments_for_rent_classified_100K.csv',sep=";",  encoding='cp1252')

C:\Users\ramac\AppData\Local\Temp\ipykernel_17340\228531961.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_100k = pd.read_csv('apartments_for_rent_classified_100K.csv',sep=";",  encoding='cp1252')

In [32]:
df_100k.shape

(99492, 22)

In [33]:
df_100k.describe()

,id,bathrooms,bedrooms,price,square_feet,latitude,longitude,time
count,9.949200e+04,99429.000000,99368.000000,99491.000000,99492.000000,99467.000000,99467.000000,9.949200e+04
mean,5.358321e+09,1.445323,1.728212,1527.057281,956.430688,36.947988,-91.568656,1.559665e+09
std,1.847404e+08,0.547021,0.749200,904.245882,417.571522,4.599461,15.817168,1.105077e+07
min,5.121046e+09,1.000000,0.000000,100.000000,101.000000,19.573800,-159.369800,1.544174e+09
25%,5.197950e+09,1.000000,1.000000,1013.000000,729.000000,33.746500,-104.791900,1.550832e+09
50%,5.508673e+09,1.000000,2.000000,1350.000000,900.000000,37.228200,-84.562300,1.568745e+09
75%,5.509007e+09,2.000000,2.000000,1795.000000,1115.000000,39.953000,-77.608200,1.568767e+09
max,5.669439e+09,9.000000,9.000000,52500.000000,50000.000000,64.833200,-68.778800,1.577391e+09

#### Checking the number of nan's in each column

In [35]:
for col in df_100k.columns:
    print(str(col)+'----->'+str((df_100k[col].isna().sum()/df_100k.shape[0])*100))

id----->0.0
category----->0.0
title----->0.0
body----->0.0
amenities----->16.125919671933424
bathrooms----->0.06332167410445061
bedrooms----->0.12463313633256945
currency----->0.0
fee----->0.0
has_photo----->0.0
pets_allowed----->60.73252120773529
price----->0.0010051059381658827
price_display----->0.0010051059381658827
price_type----->0.0
square_feet----->0.0
address----->92.01644353314839
cityname----->0.30354199332609655
state----->0.30354199332609655
latitude----->0.02512764845414707
longitude----->0.02512764845414707
source----->0.0
time----->0.0

#### Removing the columns with most nan's

In [37]:
df_100k.drop(['address'],axis = 1,inplace=True)

#### Filling nan with mean values

In [39]:
df_100k['bathrooms'] = df_100k['bathrooms'].fillna(1.4)

In [40]:
df_100k['bedrooms'] = df_100k['bedrooms'].fillna(1.7)

In [41]:
df_100k.drop(['id'],axis = 1,inplace = True)

### Identifying the columns with categorical data

In [43]:
for col in df_100k.columns:
    if df_100k[col].dtype == 'object':
        print(str(col)+'----->'+str(df_100k[col].nunique()))
print()
for col in df_100k.columns:
    if df_100k[col].dtype == 'object' and df_100k[col].nunique()<10:
        print(str(col)+'----->'+str(df_100k[col].unique()))

category----->7
title----->58503
body----->94503
amenities----->9827
currency----->1
fee----->2
has_photo----->3
pets_allowed----->4
price_display----->3718
price_type----->3
cityname----->2979
state----->51
source----->25

category----->['housing/rent/apartment' 'housing/rent/home' 'housing/rent/short_term'
 'housing/rent' 'housing/rent/condo' 'housing/rent/other'
 'housing/rent/commercial/retail']
currency----->['USD']
fee----->['No' 'Yes']
has_photo----->['Thumbnail' 'No' 'Yes']
pets_allowed----->['Cats' 'Cats,Dogs' nan 'Dogs' 'Cats,Dogs,None']
price_type----->['Monthly' 'Weekly' 'Monthly|Weekly']

In [44]:
df_100k.drop(['currency'],axis = 1,inplace=True)

In [45]:
df_100k['category'].unique()

array(['housing/rent/apartment', 'housing/rent/home',
       'housing/rent/short_term', 'housing/rent', 'housing/rent/condo',
       'housing/rent/other', 'housing/rent/commercial/retail'],
      dtype=object)

In [46]:
df_100k.drop(['title','body','price_display'],axis = 1,inplace=True)

In [47]:
df_100k['price_type'].head()

0    Monthly
1    Monthly
2    Monthly
3    Monthly
4    Monthly
Name: price_type, dtype: object

In [48]:
df_100k['amenities'].nunique()

9827

###  One Hotencoding

In [50]:
for col in df_100k.columns:
    if df_100k[col].dtype == 'object':
        print(col)
        if df_100k[col].nunique() < 20:
            # One-hot encoding for columns with fewer than 20 unique values
            df_100k = pd.get_dummies(df_100k, columns=[col], prefix=col)
        else:
            # Calculate mean sales for target encoding
            mean_sales = df_100k.groupby(col)['price'].mean()
            # Create a new column for target encoding
            col_n = f"{col}-trgt_encdn"
            df_100k[col_n] = df_100k[col].map(mean_sales)


for col in df_100k.columns:
    try:
        df_100k[col] = df_100k[col].astype(int)
    except Exception as e:
        pass

category
amenities
fee
has_photo
pets_allowed
price_type
cityname
state
source

In [51]:
df_100k.columns

Index(['amenities', 'bathrooms', 'bedrooms', 'price', 'square_feet',
       'cityname', 'state', 'latitude', 'longitude', 'source', 'time',
       'category_housing/rent', 'category_housing/rent/apartment',
       'category_housing/rent/commercial/retail',
       'category_housing/rent/condo', 'category_housing/rent/home',
       'category_housing/rent/other', 'category_housing/rent/short_term',
       'amenities-trgt_encdn', 'fee_No', 'fee_Yes', 'has_photo_No',
       'has_photo_Thumbnail', 'has_photo_Yes', 'pets_allowed_Cats',
       'pets_allowed_Cats,Dogs', 'pets_allowed_Cats,Dogs,None',
       'pets_allowed_Dogs', 'price_type_Monthly', 'price_type_Monthly|Weekly',
       'price_type_Weekly', 'cityname-trgt_encdn', 'state-trgt_encdn',
       'source-trgt_encdn'],
      dtype='object')

In [52]:
for col in df_100k.columns:
    if df_100k[col].dtype == 'object':
        df_100k.drop([col],axis =1,inplace= True)

In [53]:
len(df_100k.columns)

30

In [54]:
df_100k.describe()

,bathrooms,bedrooms,price,square_feet,latitude,longitude,time,category_housing/rent,category_housing/rent/apartment,category_housing/rent/commercial/retail,...,pets_allowed_Cats,"pets_allowed_Cats,Dogs","pets_allowed_Cats,Dogs,None",pets_allowed_Dogs,price_type_Monthly,price_type_Monthly|Weekly,price_type_Weekly,cityname-trgt_encdn,state-trgt_encdn,source-trgt_encdn
count,99492.000000,99492.000000,99491.000000,99492.000000,99467.000000,99467.000000,9.949200e+04,99492.000000,99492.000000,99492.000000,...,99492.000000,99492.000000,99492.00000,99492.000000,99492.000000,99492.00000,99492.000000,99190.000000,99190.000000,99492.000000
mean,1.417340,1.727305,1527.057281,956.430688,36.947988,-91.568656,1.559665e+09,0.000070,0.999387,0.000422,...,0.018524,0.372864,0.00001,0.001276,0.999960,0.00001,0.000030,1525.488586,1525.490329,1526.175944
std,0.531555,0.749174,904.245882,417.571522,4.599461,15.817168,1.105077e+07,0.008388,0.024754,0.020542,...,0.134837,0.483569,0.00317,0.035705,0.006341,0.00317,0.005491,612.163590,456.662243,90.152023
min,1.000000,0.000000,100.000000,101.000000,19.573800,-159.369800,1.544174e+09,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,288.000000,791.750000,800.000000
25%,1.000000,1.000000,1013.000000,729.000000,33.746500,-104.791900,1.550832e+09,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,1.000000,0.00000,0.000000,1149.568627,1173.402131,1532.000000
50%,1.000000,2.000000,1350.000000,900.000000,37.228200,-84.562300,1.568745e+09,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,1.000000,0.00000,0.000000,1344.428571,1483.243243,1532.000000
75%,2.000000,2.000000,1795.000000,1115.000000,39.953000,-77.608200,1.568767e+09,0.000000,1.000000,0.000000,...,0.000000,1.000000,0.00000,0.000000,1.000000,0.00000,0.000000,1685.518927,1645.457576,1532.000000
max,9.000000,9.000000,52500.000000,50000.000000,64.833200,-68.778800,1.577391e+09,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.00000,1.000000,30000.000000,2729.193548,8153.000000

In [55]:
df_100k.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 30 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   bathrooms                                99492 non-null  int32
 1   bedrooms                                 99492 non-null  int32
 2   price                                    99491 non-null  float64
 3   square_feet                              99492 non-null  int32
 4   latitude                                 99467 non-null  float64
 5   longitude                                99467 non-null  float64
 6   time                                     99492 non-null  int32
 7   category_housing/rent                    99492 non-null  int32
 8   category_housing/rent/apartment          99492 non-null  int32
 9   category_housing/rent/commercial/retail  99492 non-null  int32
 10  category_housing/rent/condo              99492 non-null  int32
 11  category_housing/rent/home               99492 non-null  int32
 12  category_housing/rent/other              99492 non-null  int32
 13  category_housing/rent/short_term         99492 non-null  int32
 14  amenities-trgt_encdn                     83448 non-null  float64
 15  fee_No                                   99492 non-null  int32
 16  fee_Yes                                  99492 non-null  int32
 17  has_photo_No                             99492 non-null  int32
 18  has_photo_Thumbnail                      99492 non-null  int32
 19  has_photo_Yes                            99492 non-null  int32
 20  pets_allowed_Cats                        99492 non-null  int32
 21  pets_allowed_Cats,Dogs                   99492 non-null  int32
 22  pets_allowed_Cats,Dogs,None              99492 non-null  int32
 23  pets_allowed_Dogs                        99492 non-null  int32
 24  price_type_Monthly                       99492 non-null  int32
 25  price_type_Monthly|Weekly                99492 non-null  int32
 26  price_type_Weekly                        99492 non-null  int32
 27  cityname-trgt_encdn                      99190 non-null  float64
 28  state-trgt_encdn                         99190 non-null  float64
 29  source-trgt_encdn                        99492 non-null  int32
dtypes: float64(6), int32(24)
memory usage: 13.7 MB

### Model building

#### Finding outliers

In [260]:
import pandas as pd
from scipy import stats

# Example DataFrame (replace with your actual DataFrame)
# df_100k = pd.read_csv('your_data.csv')

for col in df_100k.columns:
    if df_100k[col].nunique() > 3:
        z_scores = stats.zscore(df_100k[col])
        outliers = df_100k[(z_scores > 3) | (z_scores < -3)]
        
        # Get unique outlier values
        unique_outliers = outliers[col].unique()
        
        print(f"{col} -- unique outliers --> {unique_outliers.tolist()}")

bathrooms -- unique outliers --> [4, 7, 5, 8, 6, 9]
bedrooms -- unique outliers --> [4, 5, 7, 8, 6, 9]
price -- unique outliers --> []
square_feet -- unique outliers --> [3077, 4650, 3350, 2831, 2628, 2900, 3800, 2598, 3740, 2800, 2613, 2528, 2440, 2232, 2516, 3200, 4614, 2500, 2239, 4355, 3208, 4900, 2562, 4408, 2751, 2330, 2650, 2328, 2673, 2280, 4075, 3156, 2837, 2829, 2238, 2629, 2450, 3071, 2281, 2702, 2283, 3127, 2593, 2300, 2661, 3114, 3011, 2808, 2680, 2446, 3369, 3173, 2494, 4555, 2995, 3807, 4480, 2322, 2710, 4733, 4000, 2302, 2288, 2922, 2371, 2678, 4970, 2400, 2567, 3140, 3106, 2421, 3630, 2844, 2670, 4741, 2474, 3580, 2986, 3250, 3213, 2340, 2425, 5700, 2980, 2214, 2428, 3036, 2242, 2535, 2436, 2426, 2224, 2982, 2448, 3525, 2383, 2467, 3000, 2348, 2336, 2823, 2218, 3820, 2392, 2303, 3148, 8716, 2777, 2427, 3280, 2746, 2441, 3400, 2420, 2828, 2916, 2640, 2634, 2508, 2894, 11318, 2323, 5199, 2576, 2906, 2486, 3595, 2700, 2247, 2546, 3700, 3199, 3797, 2455, 2730, 2674, 2925, 4812, 2781, 2666, 3474, 2344, 2605, 2386, 2563, 3264, 3966, 2215, 2784, 2397, 2492, 2298, 2856, 2246, 2407, 3058, 2532, 2345, 3005, 2510, 4044, 4500, 2266, 2736, 2379, 2878, 2850, 2270, 5921, 3500, 2879, 2594, 3475, 2414, 3180, 2234, 2600, 2216, 2489, 2940, 2990, 2438, 2478, 2354, 2957, 3116, 3117, 3604, 2291, 4113, 2210, 2520, 3888, 2539, 3100, 2454, 2220, 2275, 2490, 2284, 2447, 3622, 3176, 3731, 5000, 2527, 4736, 3021, 2738, 2625, 5407, 2760, 2648, 3570, 3395, 3331, 2473, 2225, 4560, 2458, 3123, 4262, 6300, 40000, 3325, 3748, 2408, 2321, 2485, 2530, 2314, 2395, 3450, 3377, 2325, 3374, 2317, 2319, 3278, 2377, 3467, 2646, 2483, 3443, 2326, 3333, 5872, 2217, 2347, 2338, 3218, 3560, 2668, 2612, 4362, 2903, 2248, 2966, 4911, 2721, 4600, 2269, 2372, 3444, 2671, 2793, 2318, 2624, 2866, 2788, 3110, 3632, 3040, 2812, 2394, 2564, 4042, 2350, 3064, 3094, 2337, 2822, 3010, 2846, 3724, 2404, 9998, 2212, 3072, 3900, 5150, 6881, 4321, 3644, 2868, 2707, 2531, 4729, 2335, 2857, 3234, 2989, 2901, 2466, 2790, 2250, 2874, 2684, 3063, 2705, 2476, 2947, 5586, 3230, 2715, 4035, 2641, 2512, 9175, 3742, 3691, 3676, 2662, 4291, 3122, 4304, 2391, 2362, 2274, 2287, 2459, 3012, 3162, 2584, 11000, 4171, 2810, 2359, 3027, 3018, 3770, 2756, 2984, 2230, 2869, 4400, 2463, 2695, 2712, 3216, 2424, 2243, 3380, 2305, 7213, 5055, 4529, 2222, 3388, 2375, 2586, 2667, 3422, 2652, 2774, 2398, 4996, 6366, 7145, 2380, 6035, 3354, 3906, 2571, 2430, 2505, 2265, 3821, 2260, 2565, 4170, 2763, 2697, 2949, 2732, 2480, 2415, 2791, 2403, 2679, 3185, 2750, 2307, 3378, 3442, 2495, 2575, 2621, 2615, 3456, 3412, 6000, 2462, 2353, 2211, 2429, 2264, 2569, 2725, 2312, 2606, 2796, 2411, 3692, 3271, 4704, 2602, 2498, 2315, 2320, 2934, 2384, 3801, 2406, 3016, 2920, 5972, 2955, 2954, 2245, 3509, 2259, 2352, 3081, 5489, 2968, 2824, 3440, 3600, 12000, 2885, 4256, 50000, 3196, 2560, 3014, 3083, 3252, 3640, 2519, 2587, 2370, 2818, 2416, 2665, 2524, 2664, 3359, 5233, 3101, 2692, 3662, 3249, 3198, 3698, 2962, 2952, 2928, 3725, 2770, 2820, 2914, 4210, 2523, 2334, 2233, 4096, 2771, 2465, 3914, 2809, 3327, 2262, 3089, 3260, 2385, 2686, 3293, 2382, 2638, 2862, 2998, 2842, 3370, 2445, 2801, 2888, 2691, 2213, 2657, 2929, 3356, 3404, 2501, 2310, 3583, 2289, 3248, 3029, 2603, 2780, 4139, 2460, 3244, 5051, 3120, 3866, 4009, 3401, 2324, 4205, 5663, 2688, 3119, 3348, 3231, 3782, 2360, 2332, 2499, 2748, 3324, 4435, 2244, 5640, 2378, 2255, 4186, 2547, 2297, 2764, 2776, 2402, 3544, 2277, 3688, 2896, 2872, 2231, 3406, 3108, 2282, 2971, 3251, 2256, 3203, 2514, 2327, 2742, 2365, 2618, 2388, 3269, 2240, 2719, 7104, 2988, 2364, 2358, 2548, 2296, 2487, 3300, 2749, 4315, 3217, 2304, 3714, 3319, 2755, 2859, 2374, 2854, 4963, 2484, 2936, 2290, 3068, 3314, 2847, 2376, 3496, 3344, 2570, 2757, 2219, 2676, 2970, 3719, 2580, 3386, 2804, 2604, 2863, 2882, 4434, 2543, 4237, 2972, 2799, 2840, 2583, 2731, 2435, 2346, 2390, 3124, 3851, 2433, 3288, 4959, 4530, 2853, 2267, 2389, 2819, 2626, 5610, 2591, 2306, 3428, 3942, 3784, 3486, 2529, 2585, 3296, 2870, 3353, 4380, 2899, 8643, 2663, 2542, 2538, 2399, 3144, 5382, 2252, 3876, 2241, 4431, 2883, 2758, 3084, 3880, 2226, 2620, 2507, 2292, 3980, 2932]
latitude -- unique outliers --> []
longitude -- unique outliers --> []
time -- unique outliers --> []
amenities-trgt_encdn -- unique outliers --> []
cityname-trgt_encdn -- unique outliers --> []
state-trgt_encdn -- unique outliers --> []
source-trgt_encdn -- unique outliers --> [1147, 1891, 1041, 2189, 2190, 2163, 1058, 800, 931, 1081, 8153, 1127, 1100, 2969, 1213, 869, 1150, 950, 2500]

In [262]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings
from sklearn.metrics import f1_score

In [264]:
df_100k = df_100k.fillna(0)
X_train,X_test,y_train,y_test = train_test_split(df_100k.drop(['price'],axis =1),df_100k['price'],test_size = 0.3,random_state = 42)

In [266]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [268]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('---------------------------')
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 568.0365
- Mean Absolute Error: 297.5065
- R2 Score: 0.6073
---------------------------
Model performance for Test set
- Root Mean Squared Error: 534.8913
- Mean Absolute Error: 297.6916
- R2 Score: 0.6461
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 568.3539
- Mean Absolute Error: 297.2091
- R2 Score: 0.6068
---------------------------
Model performance for Test set
- Root Mean Squared Error: 534.8087
- Mean Absolute Error: 297.2535
- R2 Score: 0.6462
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 568.0604
- Mean Absolute Error: 297.5350
- R2 Score: 0.6073
---------------------------
Model performance for Test set
- Root Mean Squared Error: 534.6029
- Mean Absolute Error: 297.6463
- R2 Score: 0.6465
===================================

C:\Users\ramac\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=1.17258e-19): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 424.8098
- Mean Absolute Error: 174.0135
- R2 Score: 0.7804
---------------------------
Model performance for Test set
- Root Mean Squared Error: 463.0261
- Mean Absolute Error: 219.4716
- R2 Score: 0.7348
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 16.7192
- Mean Absolute Error: 2.8973
- R2 Score: 0.9997
---------------------------
Model performance for Test set
- Root Mean Squared Error: 516.4686
- Mean Absolute Error: 213.6768
- R2 Score: 0.6700
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 164.4627
- Mean Absolute Error: 62.1884
- R2 Score: 0.9671
---------------------------
Model performance for Test set
- Root Mean Squared Error: 370.2895
- Mean Absolute Error: 163.6799
- R2 Score: 0.8304
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 264.7692
- Mean Absolute Error: 175.7489
- R2 Score: 0.9147
---------------------------
Model performance for Test set
- Root Mean Squared Error: 399.5196
- Mean Absolute Error: 204.3465
- R2 Score: 0.8026
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 291.0518
- Mean Absolute Error: 189.2024
- R2 Score: 0.8969
---------------------------
Model performance for Test set
- Root Mean Squared Error: 396.7452
- Mean Absolute Error: 208.8174
- R2 Score: 0.8053
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 1030.8118
- Mean Absolute Error: 877.7424
- R2 Score: -0.2932
---------------------------
Model performance for Test set
- Root Mean Squared Error: 1049.2786
- Mean Absolute Error: 879.8001
- R2 Score: -0.3619
===================================

In [ ]:
df_100k['price']

### Building model without outliers

In [61]:
# df_100k_1 = df_100k.drop(['bedrooms','source-trgt_encdn'],axis = 1)

In [270]:
X_train,X_test,y_train,y_test = train_test_split(df_100k.drop(['price'],axis =1),df_100k_1['price'],test_size = 0.3,random_state = 42)

In [272]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('---------------------------')
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 568.0365
- Mean Absolute Error: 297.5065
- R2 Score: 0.6073
---------------------------
Model performance for Test set
- Root Mean Squared Error: 534.8913
- Mean Absolute Error: 297.6916
- R2 Score: 0.6461
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 568.3539
- Mean Absolute Error: 297.2091
- R2 Score: 0.6068
---------------------------
Model performance for Test set
- Root Mean Squared Error: 534.8087
- Mean Absolute Error: 297.2535
- R2 Score: 0.6462
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 568.0604
- Mean Absolute Error: 297.5350
- R2 Score: 0.6073
---------------------------
Model performance for Test set
- Root Mean Squared Error: 534.6029
- Mean Absolute Error: 297.6463
- R2 Score: 0.6465
===================================

C:\Users\ramac\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=1.17258e-19): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 424.8098
- Mean Absolute Error: 174.0135
- R2 Score: 0.7804
---------------------------
Model performance for Test set
- Root Mean Squared Error: 463.0261
- Mean Absolute Error: 219.4716
- R2 Score: 0.7348
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 16.7192
- Mean Absolute Error: 2.8973
- R2 Score: 0.9997
---------------------------
Model performance for Test set
- Root Mean Squared Error: 498.0852
- Mean Absolute Error: 211.8439
- R2 Score: 0.6931
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 163.4364
- Mean Absolute Error: 62.3709
- R2 Score: 0.9675
---------------------------
Model performance for Test set
- Root Mean Squared Error: 374.4756
- Mean Absolute Error: 163.7486
- R2 Score: 0.8265
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 264.7692
- Mean Absolute Error: 175.7489
- R2 Score: 0.9147
---------------------------
Model performance for Test set
- Root Mean Squared Error: 399.5196
- Mean Absolute Error: 204.3465
- R2 Score: 0.8026
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 291.0518
- Mean Absolute Error: 189.2024
- R2 Score: 0.8969
---------------------------
Model performance for Test set
- Root Mean Squared Error: 396.7452
- Mean Absolute Error: 208.8174
- R2 Score: 0.8053
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 1251.1587
- Mean Absolute Error: 1126.0541
- R2 Score: -0.9052
---------------------------
Model performance for Test set
- Root Mean Squared Error: 1267.4418
- Mean Absolute Error: 1129.9736
- R2 Score: -0.9871
===================================

In [274]:
df_100k.columns

Index(['bathrooms', 'bedrooms', 'price', 'square_feet', 'latitude',
       'longitude', 'time', 'category_housing/rent',
       'category_housing/rent/apartment',
       'category_housing/rent/commercial/retail',
       'category_housing/rent/condo', 'category_housing/rent/home',
       'category_housing/rent/other', 'category_housing/rent/short_term',
       'amenities-trgt_encdn', 'fee_No', 'fee_Yes', 'has_photo_No',
       'has_photo_Thumbnail', 'has_photo_Yes', 'pets_allowed_Cats',
       'pets_allowed_Cats,Dogs', 'pets_allowed_Cats,Dogs,None',
       'pets_allowed_Dogs', 'price_type_Monthly', 'price_type_Monthly|Weekly',
       'price_type_Weekly', 'cityname-trgt_encdn', 'state-trgt_encdn',
       'source-trgt_encdn'],
      dtype='object')

In [276]:
df_100k['bedrooms'].unique()

array([1, 3, 2, 4, 0, 5, 7, 8, 6, 9])

In [278]:
cols = ['bathrooms', 'bedrooms', 'square_feet', 'cityname', 'price']

In [280]:
df_100k.shape

(99492, 30)

In [282]:
df_100k.columns

Index(['bathrooms', 'bedrooms', 'price', 'square_feet', 'latitude',
       'longitude', 'time', 'category_housing/rent',
       'category_housing/rent/apartment',
       'category_housing/rent/commercial/retail',
       'category_housing/rent/condo', 'category_housing/rent/home',
       'category_housing/rent/other', 'category_housing/rent/short_term',
       'amenities-trgt_encdn', 'fee_No', 'fee_Yes', 'has_photo_No',
       'has_photo_Thumbnail', 'has_photo_Yes', 'pets_allowed_Cats',
       'pets_allowed_Cats,Dogs', 'pets_allowed_Cats,Dogs,None',
       'pets_allowed_Dogs', 'price_type_Monthly', 'price_type_Monthly|Weekly',
       'price_type_Weekly', 'cityname-trgt_encdn', 'state-trgt_encdn',
       'source-trgt_encdn'],
      dtype='object')

In [284]:
df_100k['price'].nunique()

3688

In [286]:
df_100k_1.columns

Index(['bathrooms', 'price', 'square_feet', 'latitude', 'longitude', 'time',
       'category_housing/rent', 'category_housing/rent/apartment',
       'category_housing/rent/commercial/retail',
       'category_housing/rent/condo', 'category_housing/rent/home',
       'category_housing/rent/other', 'category_housing/rent/short_term',
       'amenities-trgt_encdn', 'fee_No', 'fee_Yes', 'has_photo_No',
       'has_photo_Thumbnail', 'has_photo_Yes', 'pets_allowed_Cats',
       'pets_allowed_Cats,Dogs', 'pets_allowed_Cats,Dogs,None',
       'pets_allowed_Dogs', 'price_type_Monthly', 'price_type_Monthly|Weekly',
       'price_type_Weekly', 'cityname-trgt_encdn', 'state-trgt_encdn'],
      dtype='object')

In [298]:
df_100k['price_per_sqrfoot'] = df_100k['square_feet']/df_100k['price']

In [302]:
df_100k[['bathrooms', 'bedrooms', 'square_feet', 'cityname-trgt_encdn','price_per_sqrfoot', 'price']]

,bathrooms,bedrooms,square_feet,cityname-trgt_encdn,price_per_sqrfoot,price
0,1,1,542,2790.870130,0.246925,2195.0
1,1,3,1500,1079.133484,1.200000,1250.0
2,2,3,1650,1243.326012,1.182796,1395.0
3,1,2,820,1898.951220,0.512500,1600.0
4,1,1,624,975.923077,0.640000,975.0
...,...,...,...,...,...,...
99487,1,1,605,1090.185135,0.775641,780.0
99488,2,2,921,1152.475884,1.132841,813.0
99489,1,1,650,2374.872180,0.490566,1325.0
99490,1,1,701,1354.746667,0.752954,931.0
99491,1,2,900,2374.872180,0.564263,1595.0

In [304]:
X_train,X_test,y_train,y_test = train_test_split(df_100k[['bathrooms', 'bedrooms', 'square_feet', 'cityname-trgt_encdn']],df_100k['price'],test_size = 0.3,random_state = 42)

In [306]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('---------------------------')
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 595.0924
- Mean Absolute Error: 294.9606
- R2 Score: 0.5690
---------------------------
Model performance for Test set
- Root Mean Squared Error: 588.8062
- Mean Absolute Error: 295.6657
- R2 Score: 0.5711
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 595.0976
- Mean Absolute Error: 294.6167
- R2 Score: 0.5690
---------------------------
Model performance for Test set
- Root Mean Squared Error: 588.8617
- Mean Absolute Error: 295.3290
- R2 Score: 0.5711
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 595.0924
- Mean Absolute Error: 294.9592
- R2 Score: 0.5690
---------------------------
Model performance for Test set
- Root Mean Squared Error: 588.8065
- Mean Absolute Error: 295.6643
- R2 Score: 0.5711
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 450.4191
- Mean Absolute Error: 205.9617
- R2 Score: 0.7531
---------------------------
Model performance for Test set
- Root Mean Squared Error: 543.8149
- Mean Absolute Error: 257.8383
- R2 Score: 0.6342
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 119.3891
- Mean Absolute Error: 42.0457
- R2 Score: 0.9827
---------------------------
Model performance for Test set
- Root Mean Squared Error: 592.0408
- Mean Absolute Error: 245.2134
- R2 Score: 0.5664
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 215.2476
- Mean Absolute Error: 99.2129
- R2 Score: 0.9436
---------------------------
Model performance for Test set
- Root Mean Squared Error: 492.2886
- Mean Absolute Error: 215.2567
- R2 Score: 0.7002
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 390.7060
- Mean Absolute Error: 240.6378
- R2 Score: 0.8142
---------------------------
Model performance for Test set
- Root Mean Squared Error: 531.5883
- Mean Absolute Error: 263.5568
- R2 Score: 0.6504
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 405.4171
- Mean Absolute Error: 248.1557
- R2 Score: 0.8000
---------------------------
Model performance for Test set
- Root Mean Squared Error: 499.0680
- Mean Absolute Error: 261.5601
- R2 Score: 0.6919
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 620.5691
- Mean Absolute Error: 429.3403
- R2 Score: 0.5313
---------------------------
Model performance for Test set
- Root Mean Squared Error: 659.5387
- Mean Absolute Error: 433.3624
- R2 Score: 0.4619
===================================

### Best model

#### Random forest regressor

In [9]:
import pandas as pd
df_10k = pd.read_csv('apartments_for_rent_classified_10K.csv',sep=";",  encoding='cp1252')

 Volume in drive C has no label.
 Volume Serial Number is 7210-D35D

 Directory of C:\Users\ramac\Projects\Data-Science-Projects\Appartment_price_project

10/03/2024  03:06 PM    <DIR>          .
10/03/2024  03:06 PM    <DIR>          ..
09/30/2024  10:21 AM    <DIR>          .ipynb_checkpoints
09/30/2024  10:19 AM       102,224,705 apartments_for_rent_classified_100K.csv
09/30/2024  10:18 AM         6,309,961 apartments_for_rent_classified_10K.csv
10/03/2024  07:53 AM    <DIR>          catboost_info
10/03/2024  03:06 PM            75,227 Untitled.ipynb
               3 File(s)    108,609,893 bytes
               4 Dir(s)  135,196,831,744 bytes free

In [79]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split

In [81]:
xgbreg = XGBRegressor()

In [89]:
df_100k = df_100k.fillna(0)

In [91]:
X_train,X_test,y_train,y_test = train_test_split(df_100k.drop(['price'],axis =1),df_100k['price'],test_size = 0.3,random_state = 42)

In [93]:
xgbreg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [97]:
for col in df_10k.columns:
    if df_10k[col].dtype == 'object':
        print(col)
        if df_100k[col].nunique() < 20:
            # One-hot encoding for columns with fewer than 20 unique values
            df_10k = pd.get_dummies(df_10k, columns=[col], prefix=col)
        else:
            # Calculate mean sales for target encoding
            mean_sales = df_10k.groupby(col)['price'].mean()
            # Create a new column for target encoding
            col_n = f"{col}-trgt_encdn"
            df_10k[col_n] = df_10k[col].map(mean_sales)


for col in df_10k.columns:
    try:
        df_10k[col] = df_10k[col].astype(int)
    except Exception as e:
        pass

category

KeyError: 'category'

In [99]:
df_10k.category

0       housing/rent/apartment
1       housing/rent/apartment
2       housing/rent/apartment
3       housing/rent/apartment
4       housing/rent/apartment
                 ...
9995    housing/rent/apartment
9996    housing/rent/apartment
9997    housing/rent/apartment
9998    housing/rent/apartment
9999    housing/rent/apartment
Name: category, Length: 10000, dtype: object

In [ ]:
mae = mean_absolute_error(df_10k['price'], predicted)
mse = mean_squared_error(true, predicted)
rmse = np.sqrt(mean_squared_error(true, predicted))
r2_square = r2_score(true, predicted)